// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vitus.Infrastructure.Data;

#nullable disable

namespace Vitus.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611142415_AddAuditoria")]
    partial class AddAuditoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vitus.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acao");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detalhes");

                    b.Property<string>("EntidadeAfetada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade_afetada");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidade_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuario_nome");

                    b.HasKey("Id")
                        .HasName("pk_auditorias");

                    b.ToTable("auditorias", (string)null);
                });

            modelBuilder.Entity("Vitus.Domain.Entities.Consulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Anotacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("anotacoes");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_consulta");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("medico_id");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<Guid>("ProntuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("prontuario_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_consultas");

                    b.HasIndex("MedicoId")
                        .HasDatabaseName("ix_consultas_medico_id");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("ix_consultas_paciente_id");

                    b.HasIndex("ProntuarioId")
                        .HasDatabaseName("ix_consultas_prontuario_id");

                    b.ToTable("consultas", (string)null);
                });

            modelBuilder.Entity("Vitus.Domain.Entities.Medico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("crm");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("especialidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_medicos");

                    b.HasIndex("CRM")
                        .IsUnique()
                        .HasDatabaseName("ix_medicos_crm");

                    b.ToTable("medicos", (string)null);
                });

            modelBuilder.Entity("Vitus.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AceitaTermos")
                        .HasColumnType("boolean")
                        .HasColumnName("aceita_termos");

                    b.Property<string>("CartaoSus")
                        .HasColumnType("text")
                        .HasColumnName("cartao_sus");

                    b.Property<string>("Cpf")
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("text")
                        .HasColumnName("estado_civil");

                    b.Property<string>("InformacoesAdicionais")
                        .HasColumnType("text")
                        .HasColumnName("informacoes_adicionais");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeMae")
                        .HasColumnType("text")
                        .HasColumnName("nome_mae");

                    b.Property<string>("NomePai")
                        .HasColumnType("text")
                        .HasColumnName("nome_pai");

                    b.Property<string>("Profissao")
                        .HasColumnType("text")
                        .HasColumnName("profissao");

                    b.Property<string>("Sexo")
                        .HasColumnType("text")
                        .HasColumnName("sexo");

                    b.HasKey("Id")
                        .HasName("pk_pacientes");

                    b.ToTable("pacientes", (string)null);
                });

            modelBuilder.Entity("Vitus.Domain.Entities.Prontuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.HasKey("Id")
                        .HasName("pk_prontuarios");

                    b.HasIndex("PacienteId")
                        .IsUnique()
                        .HasDatabaseName("ix_prontuarios_paciente_id");

                    b.ToTable("prontuarios", (string)null);
                });

            modelBuilder.Entity("Vitus.Domain.Entities.Receita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("uuid")
                        .HasColumnName("consulta_id");

                    b.Property<Guid?>("ProntuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("prontuario_id");

                    b.HasKey("Id")
                        .HasName("pk_receitas");

                    b.HasIndex("ConsultaId")
                        .HasDatabaseName("ix_receitas_consulta_id");

                    b.HasIndex("ProntuarioId")
                        .HasDatabaseName("ix_receitas_prontuario_id");

                    b.ToTable("receitas", (string)null);
                });

            modelBuilder.Entity("Vitus.Domain.Entities.Triagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NomeEnfermeiro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_enfermeiro");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<string>("PressaoArterial")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pressao_arterial");

                    b.Property<Guid>("ProntuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("prontuario_id");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("numeric")
                        .HasColumnName("temperatura");

                    b.HasKey("Id")
                        .HasName("pk_triagens");

                    b.HasIndex("ProntuarioId")
                        .HasDatabaseName("ix_triagens_prontuario_id");

                    b.ToTable("triagens", (string)null);
                });

            modelBuilder.Entity("Vitus.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Vitus.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("Vitus.Domain.Entities.Medico", null)
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consultas_medicos_medico_id");

                    b.HasOne("Vitus.Domain.Entities.Paciente", null)
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consultas_pacientes_paciente_id");

                    b.HasOne("Vitus.Domain.Entities.Prontuario", null)
                        .WithMany("Consultas")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consultas_prontuarios_prontuario_id");
                });

            modelBuilder.Entity("Vitus.Domain.Entities.Prontuario", b =>
                {
                    b.HasOne("Vitus.Domain.Entities.Paciente", null)
                        .WithOne("Prontuario")
                        .HasForeignKey("Vitus.Domain.Entities.Prontuario", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prontuarios_pacientes_paciente_id");
                });

            modelBuilder.Entity("Vitus.Domain.Entities.Receita", b =>
                {
                    b.HasOne("Vitus.Domain.Entities.Consulta", null)
                        .WithMany()
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receitas_consultas_consulta_id");

                    b.HasOne("Vitus.Domain.Entities.Prontuario", null)
                        .WithMany("Receitas")
                        .HasForeignKey("ProntuarioId")
                        .HasConstraintName("fk_receitas_prontuarios_prontuario_id");

                    b.OwnsMany("Vitus.Domain.ValueObjects.Medicamento", "Medicamentos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Dosagem")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("dosagem");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("nome");

                            b1.Property<string>("Posologia")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("posologia");

                            b1.Property<Guid>("ReceitaId")
                                .HasColumnType("uuid")
                                .HasColumnName("receita_id");

                            b1.HasKey("Id")
                                .HasName("pk_medicamentos");

                            b1.HasIndex("ReceitaId")
                                .HasDatabaseName("ix_medicamentos_receita_id");

                            b1.ToTable("medicamentos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReceitaId")
                                .HasConstraintName("fk_medicamentos_receitas_receita_id");
                        });

                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("Vitus.Domain.Entities.Triagem", b =>
                {
                    b.HasOne("Vitus.Domain.Entities.Prontuario", "Prontuario")
                        .WithMany("Triagens")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_triagens_prontuarios_prontuario_id");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("Vitus.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Prontuario")
                        .IsRequired();
                });

            modelBuilder.Entity("Vitus.Domain.Entities.Prontuario", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Receitas");

                    b.Navigation("Triagens");
                });
#pragma warning restore 612, 618
        }
    }
}
